### ISSUE TITLE
New gTile project and organization discussion

### ISSUE THREAD

**Issue by jwarkentin** [gTile/gTile#1]
This is a general issue to discuss the details of how this project will be managed moving forward. I will leave this issue open and continue to update this list of items to discuss and any noteworthy decisions or discussion points until we are comfortable with everything.

As we discuss things and make decisions, we should keep in mind that to avoid stagnation on the project it's important to keep things nimble and avoid too much red tape. At the same time, we have to balance that with maintaining code quality and maintaining a clear direction with the project.

#### Things to discuss:
- [x] How will we handle general project direction and discussion?
  - I propose we use Gitter unless anyone has a better suggestion (new Gitter community can be found [here](https://gitter.im/gTileChat))
- [ ] How will project decisions be made?
  - I propose that any major decisions be discussed and decided with a majority vote and minor decisions can just be moved unilaterally unless or until there is concern or disagreement at which point it requires a vote.
- [ ] What will the policy be for committing, code reviews and merging pull requests?
  - I propose that we:
    - Try to keep master stable by only merging tested code
    - Perform all modifications on branches and create pull requests for code reviews that must be approved by at least one other person before they can be merged
- [ ] How will we handle tagging and pushing new releases?
  - Whatever we decide, our release process should be clearly documented
  - Ideally, any one of us should be able to do a release
  - We should establish a policy for deciding when to cut a new release
  - We should use Semantic Versioning (see http://semver.org/)
- [ ] Licensing (see issue #7 for discussion on this)
  - Currently the only reference to a license is found [here](https://github.com/gTile/gTile/blob/cacd48f1fb32d667f0b92f7e836a69d3545c2873/schemas/org.gnome.shell.extensions.gtile.gschema.xml#L313-L314). It says the license is GPLv3. This leaves us with the following options:
    - Maintain the code under the same GPLv3 license
    - Perform a separate rewrite of the code to re-license it
    - Somehow get @vibou to change the license
  - I would prefer the MIT license but if we must have GPLv3 I think that is also acceptable
- [ ] Consider options for an official code of conduct as mentioned by @StuntsPT (see also: https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)

Feel free to suggest any other discussion points to add and please contribute your thoughts in regard to what I've mentioned so far.

**Comment by scherepanov** [comment]
I will do one more commit to bring code to latest state out of original repo that did not make during migration.
As for license, original readme from vibou did not mention any license. I added GPL license, and get question why GPL not GPL3 - all Gnome is GPL3. So I changed to GPL3. And it made it to master that you cloned.
I have no preference on licensing, you can change to different, as I have not enough expertise on difference.

**Comment by jwarkentin** [comment]
Ok, if you are responsible for setting the license originally I guess I'm comfortable with changing it here but without the change being in the original it's legally ambiguous at best. MIT is a much more open license and seems to be the most widely adopted within the open source community in recent years. I always prefer it and use it on all my projects if possible.

**Comment by StuntsPT** [comment]
I'd also like to propose adding a [code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/),
Since this is now a community project, it is usually a good idea to have one.
As for licensing. As much as I prefer GPLv3 to other libre licenses, I was asked by the devs at GEO to re-license my extension's code as GPLv2 for compatibility reasons. Just something to keep in mind.
Regarding "general project direction", gitter can be very useful (for other reasons too), but for planning I propose a "Github project".
As for versioning - I'd like to suggest that when using the semantic versioning that one of the numbers (to be decided yet) to be dependent on gnome-shell version. This way, a new release can be made every time a new GS version is released. It is something that has to be done anyway, so it might as well be planned for.
I completely agree with the PR policy.
Thank you for listening!

**Comment by JMurph2015** [comment]
I like everything so far with the one exception of me being more of a Slack person over Gitter, but I don't really mind either way.  

Maybe the patch number could be like the Gnome shell version smashed together i.e. "325091", or the major-minor version only like "325"?

**Comment by jwarkentin** [comment]
I too would prefer Slack. However, I was digging in and comparing the two and I realized the major advantage of Gitter is that you can sign in with your Github account rather than having to create a new account. It's really designed around Github discussion and a purpose-built tool will almost certainly be better suited to our needs. It will also lower the barrier to entry for anyone in the community to participate in discussion. As such, I setup a new community on Gitter which you can find [here](https://gitter.im/gTileChat). Should we give it a go and then change if we don't like it?

**Comment by jwarkentin** [comment]
As far as versioning goes, I don't see why we couldn't do a new release with each new GS version as it stands. For the sake of everyone participating I'll copy the semver summary here:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards-compatible manner, and
> 3. PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

Given that definition, we could easily just bump the minor or patch number with each new GS release.

**Comment by scherepanov** [comment]
Well, if you have time on your hands...
Original code from vibou and contributors did not shine with high quality. You can see several generations of changes, leaving some hangs and making very convoluted code path in some cases.
I had intention just to add keyboard shortcuts and not to modify original code that handle mouse.
As much as I did not want to touch original code, I had to modify it in several cases.
That to say, redesigning mouse code part and streamlining it can be a good idea, if you have time.
Mine code also of not very high quality - it was JS learning project for me. For example, I have not figured out how to share globals between two files, ending up with defining same globals twice. And etc.
I do observe some strange behavior of gTile installation/deinstallation on my PC, which I do not know where to attribute - to buggy version of Gnome, new Gnome API or some incorrect implementation on my part.
There is one incomplete request from users - to support HiDPI. It took me a long time to figure out how to do it. Mostly due to amazing complete absence of any Gnome documentation. Had to dig into code of other extensions. 
But, with last PR I just submitted, gTile is quite usable. I am using it whole day at office, very handy. I am using almost exclusively keyboard presets, resorting to keyboard resizing/move when no suitable presets. A very handy extension.
I am planning to push this code into extensions.gnome.org ASAP. Too many users complaining about bugs that were fixed a while ago.

**Comment by StuntsPT** [comment]
@scherepanov check out #3 for the code quality issue. It's a first effort, but we can take it up from there.

**Comment by gqmelo** [comment]
I've just got interested in this extension as I'm testing Ubuntu 17.10 and this feature is essential for me. I didn't get a chance to test gTile yet as I just tried the one from Gnome extensions website.

But just a note regarding the license. You should be careful about changing the license. To change the license you should get permission from each contributor. And if the previous project didn't mention any license it means that it's actually proprietary (not public). Not sure how a project without license and with many contributors would work though. Anyway I think you would better off explicitly asking for permission to change the license to avoid any legal issue in the future.

**Comment by gqmelo** [comment]
@scherepanov  only now I noticed you wrote this:

```
Currently the only reference to a license is found here. It says the license is GPLv3. This leaves us with the following options:

    Maintain the code under the same GPLv3 license
    Perform a separate rewrite of the code to re-license it
    Somehow get @vibou to change the license
```

So maybe it's safe to assume that the existing code is GLPv3, but you should definitely reach out to each contributor if you want to change to MIT. Not only @vibou, because unless he made each contributor sign an CLA, he does not have the power to relicense the whole code. I hope I'm not too picky about this, but we've seen a lot of nasty histories about licensing. So better to be safe.

**Comment by kankaristo** [comment]
The "Add yours" page at extensions.gnome.org (the extension upload page) requires you to check a checkbox that says:
> I verify that my extension can be distributed under the terms of the GPLv2+

So, extensions.gnome.org basically requires compatibility with GPLv2+, and I'm not sure the MIT license is compatible, since it's permissible and GPL is not.

I also prefer MIT for my own projects, but changing the license of a project that has multiple contributors is messy, if not impossible.

(Disclaimer: I'm just a user, not a contributor to gTile)

**Comment by maweki** [comment]
The license can not be proprietary since the original author uploaded it to extensions.gnome.org and it is necessary to be gp2l compatible for us to distribute it.

So whatever licence the authors originally intended, it must have been one that is compatible with gpl2, even if implicitly.

**Comment by StuntsPT** [comment]
I have created #7 for discussing licensing issues, so that we can keep #1 focused on "general discussion and organization".
Please head to #7 for license discussions.
@jwarkentin can you please add a link to #7 on the OP, please?

**Comment by jwarkentin** [comment]
@scherepanov Have you heard anything back from the mailing list? Also, can you please join the Gitter chat [here](https://gitter.im/gTileChat) so we can discuss this further without spamming here. Thanks!

**Comment by scherepanov** [comment]
@maweki Submitted 3 requests for joining gnome-shell-list, did not get any reaction.
May be I should contact someone directly to reassign ownership of extension?

**Comment by scherepanov** [comment]
New version of gTile is on e.g.o.
Thats complete initial step for gTile organization.
Good job everybody!

**Comment by vibou** [comment]
Hi everyone. You don't know how honored I am. I didn't know this project would go this far and would be supported by many contributors. You have been added so many feature that's great and you did well by migrating to a new git repository. It will be easier to manage! So thank you everyone for supporting and contributing to this plug-in. 

See you very soon :) 

Vibou.
