### ISSUE TITLE
Resize and move based on grid

### ISSUE THREAD

**Issue by Strauman** [gTile/gTile#112]
First - thank you for the app! It is amazing and I use it every day :heart: 

So I have a feature request. I would love a feature that mimics the functions that today requires the gTile dialog to be open, to global keyboard shortcuts.

More specifically I want global keyboard shortcuts to 
- resize and move the current window according to a predefined grid, and
- change said grid.
All of this without opening the gTile dialog (the dialog that pops up with Super+Enter by default).

**Comment by scherepanov** [comment]
That is problematic, due to large number of shortcuts needed for move/resize.
You need 4 keys for move up/down/left/right, and additional 4 for resize.
Very natural is to use arrow keys for move, and <Shift>arrows for resize.
I cannot grab arrows in global shortcuts, as it will change UI.
Assigning other shortcuts... it would be hard to learn and remember. Though, some people like to use eMacs/vi movement keys.
Personally I am using gTile exactly in a way you describe - <Super>Enter to activate, arrows / <Shift> arrows to move/resize, Enter to place window. It works quite well, I am doing it without thinking.
Sorry, I do not see that adding global shortcuts for move/resize would improve much above workflow.

**Comment by Strauman** [comment]
Okay, I hear you! I can appreciate that you don't want to spend time doing something that you don't see the use of for your own workflow. I'm still convinced it would be an improvement in my workflow. Maybe I'll take it upon myself to do this one day.

I love shortcuts, and usually don't have any trouble remembering them when I just start using them  I was just hoping that it wouldn't be too much work to implement as an optional feature.

Also. I did the maths.
With at least 51 keys that can be used in combination with 4 modifiers that should be 714 shortcuts. That's not included shift-only keys (for cap. letters) or special keys like F-keys, arrow keys, home/end and numpad etc. (ofc. there are many already taken, but still).

No worries though. The workflow, as you say, is working quite well :+1: 
Anyways, thanks for your time :slightly_smiling_face:

**Comment by scherepanov** [comment]
Well, your request still can be implemented.
You can mark each keyboard shortcut as global. If shortcut is marked as global, it works always. If now, it works only when gTile window shown up.
Go ahead, do some coding and submit PR, I will accept it

**Comment by scherepanov** [comment]
Can you check that master works on your version of gnome-shell?

**Comment by scherepanov** [comment]
I just committed fix for gnome-shell 3.36
Can you check that it works gnome-shell v 3.28 that you have
