### ISSUE TITLE
Add right click option to open settings/preferences directly from Gnome tray icon

### ISSUE THREAD

**Issue by ElijahLynn** [gTile/gTile#241]
As a new user, I found myself right clicking on the Gnome tray icon to try to get to advanced settings to:
* Find out the name of the extension (I had forgotten, and therefore didn't know how to get to the GitHub repo to look at the README)
* Get to configuration options/settings/preferences

![image](https://user-images.githubusercontent.com/1504756/137775613-3a01f53c-bfa3-4ea5-b41b-209af0a300ff.png)

In addition, the current README has instructions for an older version of Gnome and suggests using the Gnome Tweak tool to access the extension settings, which has moved out of Gnome Tweak and into its own "Extensions" app now. 

So, I was thinking that allowing a user to right click the icon to launch that window would be an enhanced user experience, especially for new users.

**Comment by scherepanov** [comment]
Generally speaking, right button clicks is a bad idea. Primary because fo gesture interface potentially became widespread.
Though, I do think that adding a button to GUI to call preferences dialog would be a nice addition.
From other side, there is nothing in Preferences dialog that need to be changed during normal workflow. You set it once and forget. And, rarely used elements on GUI are not good.
Taking above into consideration. I am closing this ticket.
Let me know if you have different opinion.
