### ISSUE TITLE
Gaps at bottom of tiling when using preset that should fill desktop

### ISSUE THREAD

**Issue by hermidalc** [gTile/gTile#277]
While the issue wrt to mutter has been resolved, there seems to have been a change in the way gTile processes resize preset dimensions? Here's one of my presets:

96x64 0:0 44:33, 45:0 95:33, 0:34 44:63, 45:34 95:63

Before the mutter issue this used to make 4 gnome-terminals that would fill my desktop without any gaps except for a very small one between the top left and top right terminals (requiring  a manual adjustment, but this is understandable given how gnome-terminal has to size relevant to the terminal font and your screen resolution)

But now the bottom two terminals, which used to tile perfectly without any gaps, are a bit off:

![Screenshot from 2022-02-20 09-53-05](https://user-images.githubusercontent.com/461066/154848612-67f540f1-bfa5-4185-bc51-0adaf771d5e6.png)

Also in non gnome-terminal apps, https://github.com/gTile/gTile/issues/267#issuecomment-1046256198

_Originally posted by @hermidalc in https://github.com/gTile/gTile/issues/267#issuecomment-1046255132_

**Comment by hermidalc** [comment]
Also in non gnome-terminal apps, https://github.com/gTile/gTile/issues/267#issuecomment-1046256198

**Comment by scherepanov** [comment]
Well. You are dealing with rounding errors.
To see details, enable logging according instructions in README.md.
You will find pixel coordinates on screen where window is placed.
With large grid size, rounding errors became very visible.
We addressed rounding errors in keyboard shortcuts - should be working properly, please check!
But rounding errors not fixed for manual grid placement.
Workaround would be to use smallish grid sizes, like 2x2.
I am not sure why you have not seen rounding errors before.
I suggest you will do some coding and submit pr with fix.  I will point you into right direction, help with testing, and will accept proper fix.

**Comment by scherepanov** [comment]
May be, this problem (gap) was introduced recently, and you pick up recent code.
Would be interesting to find what is going on.
Please enable logging and do some research

**Comment by scherepanov** [comment]
I checked your preset:
96x64 0:0 44:33, 45:0 95:33, 0:34 44:63, 45:34 95:63
It does not work with current code in master. We changed way how presets are defined, now tiles are numbered from 1, instead of 0, and end on 64 instead of 63:
96x64 1:1 44:33, 45:1 96:33, 1:34 44:64, 45:34 96:64
Recent code behaves properly and do not display any problems you described.
Most likely you are running code from EGO (extension.gnome.org) where most recent version do behave like you described.
I would suggest to reinstall gTile from github master, change preset like I described above, and see how it works.

Your ticket actually very useful. It comes to me that migration to new version of gTile will be rough. We changed how tiles are numbered in presets. Stock presets are fine as we did required update. But, all user custom presets will suddenly stop working or work incorrectly. That is a serious problem.

**Comment by hermidalc** [comment]
Thank you @scherepanov

**Comment by hermidalc** [comment]
> I checked your preset: 96x64 0:0 44:33, 45:0 95:33, 0:34 44:63, 45:34 95:63 It does not work with current code in master. We changed way how presets are defined, now tiles are numbered from 1, instead of 0, and end on 64 instead of 63: 96x64 1:1 44:33, 45:1 96:33, 1:34 44:64, 45:34 96:64

Just upgraded to latest on EGO, to get the same placement as I had before I had to +1 to all internal dims `96x64 1:1 45:34, 46:1 96:34, 1:35 45:64, 46:35 96:64`
