### ISSUE TITLE
Popup placement

### ISSUE THREAD

**Issue by syco** [gTile/gTile#316]
Hi,

I've just installed the latest archlinux and gnome, with gtile v51 and I've a question about the popup placement:
![Screenshot from 2023-01-15 16-44-20](https://user-images.githubusercontent.com/54575/212554481-4a49ef7c-bd65-4bfa-8266-85534ac53e18.png)

I've a primary monitor on the right and a secondary monitor on the left (someone will say I'm a psycho for not having the secondary monitor on the right, but that's how I roll).

Anyway, if you look at this screenshot, the popup for the terminal appears in the center of the terminal window for the current monitor, and in the center of the second monitor for the other monitor.

Would it be possible to make them appear side by side?

Would it be possible to add a setting to make them appear side by side in the center of the primary monitor?

I hope I was able to explain it... thanks

**Comment by scherepanov** [comment]
That is by design…
Pop up appear in the middle of window with focus.
On rest of monitors pop up appear in the middle of screen.
Making popups from all screens to appear on same monitor next to each other would be confusing and will overload GUI appearance.
I suggest to use Gnome built-ins shortcuts Super-Shift-Arrows to move window with focus on desired terminal, then use gTile to place window. I am doing it that way.

**Comment by syco** [comment]
I see what you mean, in this case the 2 popups side by side would be even bigger than the terminal itself.
But, I'm using the terminal, so most likely my cursor is already in that area. When I use the shortcut to show gtile, I don't want to drag the mouse all the way to the other monitor.
I still think settings for popup placement would give the user more flexibility, usability is a very personal topic in my experience.

**Comment by scherepanov** [comment]
Do not drag mouse to other monitor!
Use Gnome built-in keyboard shortcut to move window to other monitor! Very handy!
