### ISSUE TITLE
Error --experimental_enable_bzlmod on GNOME 44.0

### ISSUE THREAD

**Issue by JakacAircision** [gTile/gTile#324]
Hello. I'm not able to install gTile on GNOME 44.0
I get the following error

~/Downloads/gTile> bazel run :install-extension
INFO: Reading rc options for 'run' from /home/User/Downloads/gTile/.bazelrc:
  Inherited 'common' options: --experimental_enable_bzlmod
ERROR: --experimental_enable_bzlmod :: Unrecognized option: --experimental_enable_bzlmod

**Comment by scherepanov** [comment]
Can you try to remove gTile dir and do clean checkout from gihub, and run install again
May be, something bazel version...

**Comment by JakacAircision** [comment]
Hi I deleted the gTile folder. I cloned the gTile master branch. I retried the bazel run :install-extension command but I get the same error.

**Comment by scherepanov** [comment]
That is definitely bazel config issue... cannot help :-(

**Comment by christ31** [comment]
> What can I do?

**Note, I'm not using bazel, so do at your own risk**

Looking through the bazel repo, are you perhaps using the version 6?

You can check with `bazel version`

If yes, Quoting from [Bazel's Github Repo Changelog](https://github.com/bazelbuild/bazel/blob/master/CHANGELOG.md#release-600-2022-12-19), starting in v6:
"--experimental_enable_bzlmod has been renamed --enable_bzlmod, and still defaults to false."

Since the error stated `"ERROR: --experimental_enable_bzlmod :: Unrecognized option: --experimental_enable_bzlmod"`

You can try to change the content from the .bazelrc file from 
`common --experimental_enable_bzlmod`
to 
`common --enable_bzlmod`

If no, then there's something broke with the bazel. You can try to reinstall though.

**Comment by JakacAircision** [comment]
bazel version
Build label: 3.7.2- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu May 6 00:00:00 2021 (1620259200)
Build timestamp: 1620259200
Build timestamp as int: 1620259200

Inherited 'common' options: --enable_bzlmod
ERROR: --enable_bzlmod :: Unrecognized option: --enable_bzlmod

I tried to force reintall bazel too. It didn't help.

**Comment by christ31** [comment]
> bazel version Build label: 3.7.2- (@non-git) Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar Build time: Thu May 6 00:00:00 2021 (1620259200) Build timestamp: 1620259200 Build timestamp as int: 1620259200
> 
> Inherited 'common' options: --enable_bzlmod ERROR: --enable_bzlmod :: Unrecognized option: --enable_bzlmod
> 
> I tried to force reintall bazel too. It didn't help.

Can you try to update to bazel version 5? seems like the option of `--experimental_enable_bzlmod` introduced in that version

**Comment by christ31** [comment]
@JakacAircision, I already tried building from source using Fedora 38 (Gnome 44). When using bazel version 5, there's error because gTile currently use bazel version 6.0.0. So, by upgrading to bazel version 6, I'm able to install it from source.

**Comment by scherepanov** [comment]
New version 52 with gnome-shell 44 support is on EGO.
