### ISSUE TITLE
set rightclick + window drag as shortcut

### ISSUE THREAD

**Issue by Ph1syc** [gTile/gTile#330]
Is it possible to make it so that if i drag a windows and press right click the menu appears? that way i can just drag it into place.

**Comment by scherepanov** [comment]
If you are dragging window, typically you are doing it by pressing and holding right mouse button, then dragging windows.
Gnome-shell does not handle additional clicks while dragging window.

FYI gTile do have a very handy keyboard-only interface.
Use Super-Enter to activate window, Space to change grid size if needed, then arrows - shift-arrows to move/resize window (instead of dragging by mouse), Enter for placing window. After little time it became automatic and you do not think about it.
