### ISSUE TITLE
gschemas.compiled missing?

### ISSUE THREAD

**Issue by singularo** [gTile/gTile#349]
I had this error:

GLib.FileError: Failed to open file “/home/simon/.local/share/gnome-shell/extensions/gTile@vibou/schemas/gschemas.compiled”: open() failed: No such file or directory

But managed to compile the file using the instructions from the THEMING.md, basically did this is the gTile dir and copied the file in where the extension is in the path as per the error. That seemed to solve it, hope helps someone else.

```
glib-compile-schemas schemas
```

**Comment by schnz** [comment]
It sounds like you extracted the extension manually to `~/.local/share/gnome-shell/extensions/gTile@vibou` instead of installing it with `gnome-extensions install -f gtile.dist.tgz` (or `npm install:extension` when building from source).

But that's just my assumption. How have you installed the extension?

**Comment by singularo** [comment]
I initially installed from source with the npm commands, then tried the release tgz (but yes, just extracted it).
I just re-tried the tgz with the gnome-extensions command, same issue, missing that gschema.compiled file.
Mantic Ubuntu, has been upgraded through many versions though, so I guess there might be some weirdness locally.

**Comment by schnz** [comment]
>  As of GNOME 44, settings schemas are compiled automatically for extensions installed with the gnome-extensions tool, GNOME Extensions website, or a compatible application like Extension Manager

-- https://gjs.guide/extensions/development/preferences.html#compiling-a-schema

---

So if you used (1) the `gnome-extensions` tool to install the extension and (2) restarted your shell-session after that and still have problems with a missing schema, then I would suggest open a bug ticket [upstream](https://gitlab.gnome.org/GNOME/gnome-shell).

**Comment by clemisch** [comment]
Thank you @singularo, manually compiling the schemas worked for me. 

FYI, I had to manually install the extension due to [a bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2821) in `gnome-extensions` when `.cache` is on another filesystem. What is not mentioned there is the necessary compilation of schemas.
