### ISSUE TITLE
Add settings to preferences, to position gTile window either at mouse cursor or center of focus window.

### ISSUE THREAD

**Issue by scherepanov** [gTile/gTile#352]
Rewrite V45 changed gTile window position behaviour - it is now placed at mouse cursor position.
We need to add settings to preferences, where to place gTile window - at mouse cursor position, or at center of focus window.
gTile window position should be shifted on open, to prevent mouse position being inside gTile window.

**Comment by schnz** [comment]
I'd support to have an option for this. I'd even make it the default to place the gTile overlay "at center of focus window" (just to keep the old behavior that users are used to). But what would be a good & consistent way to place the gTile overlay? 

> Previous version of gtile contains special code - gTile window opens in center of focus window, but not to contain mouse pointer. That makes for predictable UI with keyboard.

-- [source](https://github.com/gTile/gTile/pull/348#issuecomment-1824585105)

This is what bothered my in the original extension because it looked to me like the placement of the overlay was inconsistent. I didn't know that it evaded the cursor. Could we make it so that the window always opens at predictable position and somehow handle the case when the mouse cursor accidentally happens to hovers a tile? I am not sure what would be a good solution here.

**Comment by scherepanov** [comment]
@schnz 
This issue was reported by user a while ago.

Mouse "rarely" overlays gTile window on open. But it is causing unpredictable and annoying behavior.
The way how code works, it thinks it is intentional action by user.
I look how to address it better... have not found good solution.
Best approach is to shift gTile window out of cursor way. It works, easy to do. gTile window is not big, shift by half window size typically non intrusive and not noticeable by users.

If you think it will help, we can add one more setting to preferences: "do not shift gTile window out of cursor position"

If you would not mind, please implement when you will have a chance.

**Comment by scherepanov** [comment]
Hi @schnz , hope you are doing great.
Thanks for all the work on rewriting gTile for gnome v45!
When you will have time, can you implement this request?
When using keyboard to move/resize window, gTile now behaves very unpredictable, because gTile window popup at unpredictable place. This looks like erratic behaviour.
Also, if gTile window is open, and user is switching focus to other window, gTile popup should follow focus window.
There is no hurry, please do when you will have a chance.

**Comment by schnz** [comment]
Hey @scherepanov , unfortunately, I don't know when I find the time to do it. Maybe someone else is up for it? I have this task in the back of my head though.

**Comment by scherepanov** [comment]
No problems, I will wait :-)
Take your time!

**Comment by schnz** [comment]
I've created a _work in progress_ PR to address this issue. Please check it out when you find time (no rush) and give some feedback.

The overlay is now __consistently__ placed in the center of the focused window. I can't help but to dislike the behavior to place the overlay differently if there happens to be conflict with mouse cursor. So I refrained from implementing this behavior. It feels very random at times when the overlay is rendered at an unexpected position, only because the mouse pointer is placed in the "wrong" location. I would rather like to deal with the inconvenience that the cursor triggers the "hover tile" animation. I would really appreciate feedback/ideas on this issue.

---

On a different note: Do you happen to know how the old gTile extension managed to hide the overlay when the Gnome overview (<kbd>Super</kbd>-key) became visible? In the PR I found a way to implement this behavior - but it is different from how the old extension solved it. Yet, I can't figure out what caused this behavior in the old gTile extension. By analyzing the source code I would assume that the gTile overlay stays open when the Gnome overview is shown. But that's not the case and I would _really_ like to know why.

**Comment by scherepanov** [comment]
@schnz 
Thanks, will try over weekend. My Linux at office still Ubuntu 22.04 with previous gnome-shell version.
Hiding overlay in old gTile in Gnome overview just works, we had no code to handle it.
