### ISSUE TITLE
Gnome 47 Support

### ISSUE THREAD

**Issue by arashm** [gTile/gTile#398]
Gnome 47 has been released and I miss this extension. Thanks for the great work.

**Comment by schnz** [comment]
Just upgraded to Gnome 47 myself. I will update the extension during the weekend.

By the looks of it there are no breaking changes[1]. But there is a typing that changed w.r.t. the preferences dialog so I would like to update the TypeScript types & dependencies[2] while I am at it.

For those that are desperate and want to update immediately, you can follow the instructions here[3]

[1] https://gjs.guide/extensions/upgrading/gnome-shell-47.html
[2] https://github.com/gjsify/gnome-shell/pull/49
[3] https://github.com/gTile/gTile/issues/376#issuecomment-2015759515

**Comment by schnz** [comment]
@scherepanov I just published a new release with Gnome 47 compatibility. Can you submit it to gnome.extensions.org? 

_Technically_ there was a breaking change in the method signature of `src/prefs.js`. Hence I marked this release as incompatible with Gnome 45 and Gnome 46 - although it should continue to work with those environments. However, since there are no new features in gTile since those releases I believe it won't matter too much.

**Comment by scherepanov** [comment]
Great!
Publishing to EGO...

**Comment by scherepanov** [comment]
gTile is pending review on EGO.

**Comment by scherepanov** [comment]
gTile new release is approved on EGO.
