### ISSUE TITLE
Maximum window count in Autotile

### ISSUE THREAD

**Issue by rstacruz** [gTile/gTile#404]
**Summary:** I'd love to have a **maximum window count** setting for autotile. That is, I want 3 windows visible max at a time - anything else becomes minimised.

I'd love to help, I got quite a bit of JavaScript and TypeScript experience!

I'd love some guidance first on whether you're up for adding this to gTile, and what would be the ideal approach for this.

## Context

First of all, thank you so much for the work on gTile! I was a long time user of i3/sway, and I eventually switched to GNOME after finding that gTile does exactly what I want - a single-keypress solution to automatically lay out my windows (auto-tiling).

I find that auto-tiling a lot of windows is overwhelming, and I can only focus on 2 or 3 things at a time.

Normally my workflow is to put extra windows out of the way (usually a calendar, music player, or notepad), but it's a bit tedious and goes against my "one button" ideal.

## Prior art

The macOS window tiling utility, [Amethyst](https://github.com/ianyh/Amethyst), supports max-window-count:

> `window-max-count` - The max number of windows that may be visible on a screen at one time before additional windows are minimized. A value of 0 disables the feature.

**Comment by scherepanov** [comment]
What will be your suggestion, how to determine, what windows will be visible after autotile, and what will be minimised?

**Comment by rstacruz** [comment]
on Amethyst, it would prioritise based on the Z-index stack order. Eg, max = 2 would mean it would show the focused one, the one below it, and minimise the rest. what do you think?

**Comment by schnz** [comment]
Thanks for your feedback! The "GridSpec" feature was only added relatively recently to gTile and I assume most users of the extension are unaware of it. Good to see that it is used in practice :)

---

> I find that auto-tiling a lot of windows is overwhelming, and I can only focus on 2 or 3 things at a time.
> A: on Amethyst, it would prioritise based on the Z-index stack order. Eg, max = 2 would mean it would show the focused one, the one below it, and minimise the rest.

Correct me if I am wrong, but couldn't you use a GridSpec without dynamic rows then? For instance: `cols(1, rows(1,1))` would at most show up to 3 windows on a single monitor at a time. IIRC, Gnome also iterates over windows from "most recently focused" to "least recently focused" (i.e. the Z-Index). 

That being said, I am happy to accept a PR that extends the GridSpec, if it is useful to you and your workflow. 

---

> B: on a tile like cols(1, 1d), maybe there's a way to specify how many can fit in the 1d. Maybe something like cols(1, 1:dynamic(2)) to define that only 2 windows can fit in it or something.

You could definitely add such a change. From a syntactical/grammatical standpoint, I would probably prefer a different syntax (even if it means a breaking change - because like I said: this feature is probably not used very much). Something like this: `cols(1, 1:2d)`

**Comment by rstacruz** [comment]
hmm.. I think you're right, I can just set up an autotile like `cols(1, rows(1,1))`. Unfortunately if there are only 2 windows, there will be a hole, but I can just set up a different autotile keybinding for that case.

Thanks for the insight!
