### ISSUE TITLE
Add support for rebinding movement keys

### ISSUE THREAD

**Issue by Crote** [gTile/gTile#44]
I'm currently trying to set up gTile to use Vim-style key bindings, as I don't like using the arrow keys.

Unfortunately, while the resize keys can be rebound, the movement keys cannot.  
Adding the proper names to the `pretty_names` list in `prefs.js` would fix my issue as I want to bind `hjkl`, but this does not allow setting the default arrow bindings for some reason, so that would not be a workable solution. Is there any way to add proper support for rebinding? It seems that the limitation is solely in the key picker.

**Comment by scherepanov** [comment]
Hmmmm.... definitely some users would want something that you would never thought of...
I explicitly made move and resize keys as fixed keybinding to arrows and shift-arrows. I thought it will make it less error prone, as re-assigning arrow keys is not for vast majority of users.
BTW I am thinking to add fixed binding Ctrl-Arrows, for coordinated move of windows sharing same edge.

**Comment by JMurph2015** [comment]
Yeah, this is a pretty novel use-case, but one that I could totally see being a useful feature (I use Vim and Spacemacs a lot and so get confused when things don't work that same way).

**Comment by scherepanov** [comment]
Tried to make it, only to find same issues as described above.
Need more efforts.

**Comment by scherepanov** [comment]
I got an idea how to easy implement rebinding of movement keys.
I can add checkbox settings "use vi movement keys"
If checked, will replace arrows and shift-arrows with hjkl and shift-hjkl, like in vi.
That is rather easy and straightforward to implement.
I doubt users will want to replace arrows with something else than vi keys.
Let me know how this idea would work for you.

**Comment by scherepanov** [comment]
It is very tricky to reset key binding to default. Majority of users will not be able to do it. And binding to arrow key is not allowed. So, as soon as you will bind movement to any key, you are stuck with it and cannot (easily) change back to arrows.

**Comment by scherepanov** [comment]
Problem with binding arrow keys is that preferences dialog does not allow to bind "arrows".
I am using canned code that is there since the beginning of a time, and this code plainly reject arrows.
You cannot change binding to arrows using dialog. It is actually described at first post for this issue.
Key binding is done using built-in functions, and seems to be Gnome is rejecting binding to arrow keys.  That is understandable, as re-assigning arrow key can easily make GUI unusable, up to bricking up installation completely.
Plan is to add checkbox for rebinding keys to vim keys.
May be it is taking way too long to implement... but I cannot commit to github from office any more.

**Comment by scherepanov** [comment]
I made it working similar to vi - both arrow and keyboard (hjkl) movement are enabled at same time.
Will be released soon.
