### ISSUE TITLE
Auto-tile

### ISSUE THREAD

**Issue by FranzSkuffka** [gTile/gTile#47]
A feature that automatically tiles the windows whenever a new window is opened would be great.

**Comment by scherepanov** [comment]
That is outside of scope of gTile

**Comment by StuntsPT** [comment]
@FranzSkuffka : 
Here are two alternatives:
https://extensions.gnome.org/extension/294/shellshape/
https://extensions.gnome.org/extension/657/shelltile/

**Comment by attndeficit** [comment]
> That is outside of scope of gTile

This feature is precisely what I've been looking for as I test out these different grid window manager apps.  This comment really surprises me... I must go figure out _what_ exactly the "scope" is of gTile because quick, efficient grid-oriented window management seemed to me to be exactly what it aims to accomplish.

How might I ask does automatic tiling as I open 15 windows in quick succession not fit my current (possibly flawed) understanding of this project's "scope"?  I enter keys into all windows simultaneously and need to see them all... simultaneously, so I want to launch them in order in a grid.  I'm about to give up and write something to do this, probably a quick loop to launch my windows how and where I want.  Just had to comment, I'm honestly perplexed why this wouldn't fit with what this mod aims to do.

**Comment by scherepanov** [comment]
Initial placement of window is done deep inside gnome-shell.
To implement opening window with edges on a grid inside gTile, you need to subscribe to "new window" event, and on receiving his event try to resize/move window.
First, I do not see event "new window" published by gnome-shell.
Next, as windows are drawing after they created, it can be a strange effects if window is resized before being drawn.
And, I do not know how to handle modal/system dialogs correctly during creation.
I am pretty sure this feature implementation in gnome-shell is possible, but it requires a lot of research.
I still believe that this feature is outside scope of gTile, and better be implemented as separate extension - exactly what you are planning to do.
For tiling many windows, I can suggest you auto-tile feature fo gTile.
With shortcut, you can arrange all windows on monitor in one or several columns. And, they will be arranged in alphabetical order of title. Seems to be similar to what you want.

**Comment by wleoncio** [comment]
> @FranzSkuffka :
> Here are two alternatives:
> https://extensions.gnome.org/extension/294/shellshape/
> https://extensions.gnome.org/extension/657/shelltile/

I understand the former has been discontinued, and the latter doesn't auto-tile.

**Comment by FranzSkuffka** [comment]
I use i3 now. Thanks @wleoncio

**Comment by hakan-demirli** [comment]
If anyone still needs this feature there is  [forge](https://github.com/forge-ext/forge) extension.
