### ISSUE TITLE
Montitor hot plug-in not supported

### ISSUE THREAD

**Issue by squalou** [gTile/gTile#57]
Hello, 
looks like I'm facing the same issue as the clsoed one #42 (waiting to be reopened)
I'm running Gnome 3.30 on Arch

I have a 3-screens setup : laptop + 2 screens over display port.

Only windows on one of them can be tiled using gTile. It's not even the 'main' monito that works.

On others, I get this message when in debug :

`JS ERROR: TypeError: monitor is undefined`

Let me know whatever addition logs I can provide, maybe I can run some additional commands to get info from my monitor setups as seen from gnome ?

**Comment by squalou** [comment]
Damn !
I've just closed the extension, then then opened it again ... guess what : it works.

I suggest to keep this issue opened until I test again : maybe it's reproductible. (like, at each monitor re-connection).

Would be a pain to stop/start again the extension each time (but would be ok as a workaround).

**Comment by squalou** [comment]
I confirm discrepencies when switching from multi to single monitor, or vice-versa.

keyboard bindings get lost, only one monitorsomewhat works.

Restarting the extension fixes it.

If I knew a way to restart  an extension without having to click through  'Tweaks ' app, lik, a command line that I would bind to a key action, Woud be fine.

**Comment by squalou** [comment]
for the records : I finally read the F... manual ;) 
gnome-shell-extension-tool --r gTile@vibou

**Comment by scherepanov** [comment]
That is correct - hot monitor plug-in not supported
gTile have internal structure per monitor, that initialized on extenstion init.
If monitor count changed, or monitor resolution changed, this internal structure need to be re-initialized.
That can be done manually by disabling and enabling gTile.
gnome-shell never supported extension restart, it is actually only disabling/enabling.

Right way to address this issue is to subscribe to system event "onMonotorChange" or something like this. On this event internal structure need to be re-initialized (and some other stuff done).
I tried in past this thing, but had no hardware to really test it.
Will try to issue a fix on next coding iteration.

**Comment by squalou** [comment]
Cool, great to here that !

For now, I use a keyboard shortcut to `gnome-shell-extension-tool -d gTile@vibou && gnome-shell-extension-tool -e gTile@vibou`  

and it's already a pleasure to use ;)

**Comment by fiLLLip** [comment]
I'm experiencing this now at work with docking in and out my computer. I can as previously mentioned just deactivate and activate the extension to make it work, but that seems kind of hacky. Could it be possible with a context menu or something that could have the option of reinitializing?

Kind of like:
![image](https://user-images.githubusercontent.com/1264369/63910785-6562ff00-ca28-11e9-8c5a-7ad970ef03f7.png)

**Comment by scherepanov** [comment]
Yes this bug is well overdue.. will look to make new release soon with a fix.
