### ISSUE TITLE
Option for autotiling vertically with a shortcut

### ISSUE THREAD

**Issue by grossherr** [gTile/gTile#81]
Having an option for autotiling vertically with a shortcut would be great. So basically one column as many rows as windows.

Amazing extension, keep up the work!

**Comment by scherepanov** [comment]
Well.. vertical autotiling with one column is not present because it was a requests from users to support legacy tailing mode. And, legacy tailing mode (one window left half of screen - rest of windows tiled in one column on right) took first shortcut.
It is not a big deal to implement vertical tiling in single column (just have counter started from 1, instead of 2). It is a problem where to map this function. gTile already very heavily using all combination.
I can implement this function and leave unassigned in preferences. Means, will be no default out-of-box shortcut mapping to vertical single-column tailing. You will have to manually change settings.
Let me know if it will work for you. I can implement in one of future releases.

**Comment by grossherr** [comment]
It is useful, if you work with screens that are turned by 90 degrees, giving them more height than width. Or at least that would be my use case. 

In my mind »Autotile 10 cols« could be replaced, 9 columns are more than enough. Which would make room for a one column option, still using all the number keys. Anyhow, that's your decision. 

Leaving it unassigned definitely works for me too. Just having the option would be very nice.

Thanks for looking into it.
